USE [master]
GO

/****** Object:  Database [bhavcopy]    Script Date: 11/16/2018 5:16:34 PM ******/
CREATE DATABASE [bhavcopy]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'bhavcopy', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\bhavcopy.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'bhavcopy_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\bhavcopy_log.ldf' , SIZE = 466944KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [bhavcopy] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bhavcopy].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [bhavcopy] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [bhavcopy] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [bhavcopy] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [bhavcopy] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [bhavcopy] SET ARITHABORT OFF 
GO

ALTER DATABASE [bhavcopy] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [bhavcopy] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [bhavcopy] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [bhavcopy] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [bhavcopy] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [bhavcopy] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [bhavcopy] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [bhavcopy] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [bhavcopy] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [bhavcopy] SET  DISABLE_BROKER 
GO

ALTER DATABASE [bhavcopy] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [bhavcopy] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [bhavcopy] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [bhavcopy] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [bhavcopy] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [bhavcopy] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [bhavcopy] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [bhavcopy] SET RECOVERY FULL 
GO

ALTER DATABASE [bhavcopy] SET  MULTI_USER 
GO

ALTER DATABASE [bhavcopy] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [bhavcopy] SET DB_CHAINING OFF 
GO

ALTER DATABASE [bhavcopy] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [bhavcopy] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [bhavcopy] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [bhavcopy] SET QUERY_STORE = OFF
GO

USE [bhavcopy]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [bhavcopy] SET  READ_WRITE 
GO

